# Generated by Django 5.1.3 on 2024-11-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteToResource', '0002_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Username'),
        ),
    ]
