# Generated by Django 5.1.3 on 2024-11-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wasteToResource', '0003_alter_signup_email_alter_signup_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
